layout_spectrum: 0.15533620794303715
typography_spectrum: 0.8219572256784886
color:
  brandStrength: 0.7145091181155294
  lightness: 0.8063840749673545
  saturation: 0.25006899470463395
  rhythmicContrast: 0.8223190645221621
  brandColors:
    - '#304269'
    - '#91BED4'
    - '#D9E8F5'
    - '#FFFFFF'
    - '#F26101'
name: johnwill
